# Generated by Django 5.0.10 on 2025-03-27 08:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityzonepolicy",
            name="application",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50, null=True),
                size=20,
            ),
        ),
    ]
