# Generated by Django 5.0.10 on 2025-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_security", "0002_alter_securityzonepolicy_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityzonepolicy",
            name="index",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
