# Generated by Django 5.0.10 on 2025-03-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_security", "0003_securityzonepolicy_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firewallfilterrule",
            options={"ordering": ["index", "name"]},
        ),
        migrations.AlterModelOptions(
            name="securityzonepolicy",
            options={"ordering": ["index", "name"]},
        ),
        migrations.AddField(
            model_name="firewallfilterrule",
            name="index",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
