# Generated by Django 6.0.4 on 2026-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_security", "0028_alter_customprefix_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityzone",
            name="allow_intra_zone",
            field=models.BooleanField(default=False),
        ),
    ]
