# Generated by Django 6.0.4 on 2026-05-22 08:27

import django.core.validators
import netbox_security.fields.choice_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_security", "0029_securityzone_allow_intra_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityzonepolicy",
            name="policy_actions",
            field=netbox_security.fields.choice_field.ChoiceArrayField(
                base_field=models.CharField(max_length=20),
                size=4,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
