# Generated by Django 6.1 on 2026-09-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_security", "0031_alter_address_owner_alter_addressset_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityzoneassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(("app_label", "dcim"), ("model", "interface")),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        models.Q(("app_label", "ipam"), ("model", "prefix")),
                        models.Q(("app_label", "ipam"), ("model", "iprange")),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
