name: Lint

on:
  - push
  - pull_request

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@main

          - name: Check conformance to Black standards
            uses: psf/black@stable
            with:
                options: "--check"
                src: "netbox_security"
